=== Koulio/lightning/src/main/resources/lightning.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://github.com/automatictester/lightning"
           xmlns="https://github.com/automatictester/lightning"
           elementFormDefault="qualified">
    <xs:element name="testSet">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="maxAvgRespTimeTest" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="testName" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="transactionName" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="maxAvgRespTime" type="xs:long" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Koulio/lightning/src/test/resources/lightning.xml
<?xml version="1.0" encoding="UTF-8"?>
<testSet xmlns="https://github.com/automatictester/lightning"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://github.com/automatictester/lightning lightning.xsd">

    <maxAvgRespTimeTest>
        <testName>Test #1</testName>
        <description>Verify average login times are not longer than specified</description>
        <transactionName>Login</transactionName>
        <maxAvgRespTime>2000</maxAvgRespTime>
    </maxAvgRespTimeTest>

    <maxAvgRespTimeTest>
        <testName>Test #2</testName>
        <description>Verify average search times are not longer than specified</description>
        <transactionName>Search</transactionName>
        <maxAvgRespTime>1000</maxAvgRespTime>
    </maxAvgRespTimeTest>

</testSet>
